// packages/react-app/src/components/IpInputField.tsx
import React from "react";
import { IpInput } from "../types";
import { IpResult } from "./IpResult";
import { useIpLookup } from "../hooks/useIpLookup";

interface IpInputFieldProps {
  input: IpInput;
  index: number;
  onUpdate: (input: IpInput) => void;
  onRemove?: (id: number) => void;
}

export const IpInputField: React.FC<IpInputFieldProps> = React.memo(
  ({ input, index, onUpdate, onRemove }) => {
    const { handleBlur } = useIpLookup(onUpdate);

    return (
      <div className="ip-input-container">
        <div className="ip-input-row">
          <label className="ip-label" htmlFor={`ip-${input.id}`}>
            {index}
          </label>
          <input
            id={`ip-${input.id}`}
            type="text"
            onBlur={(e) => handleBlur(input, e.target.value)}
            disabled={input.isLoading}
            className={`ip-input ${input.error ? "error" : ""} ${
              input.result ? "success" : ""
            }`}
            aria-describedby={input.error ? `error-${input.id}` : undefined}
          />
          {onRemove && (
            <button
              className="remove-button"
              onClick={() => onRemove(input.id)}
              title="Remove IP input"
            >
              X
            </button>
          )}
          {input.isLoading && (
            <div className="spinner" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          )}
          {input.result && <IpResult result={input.result} />}
        </div>

        {input.error && (
          <div id={`error-${input.id}`} className="error-message" role="alert">
            {input.error}
          </div>
        )}
      </div>
    );
  }
);

// packages/vue-app/src/components/IpInputField.vue
<template>
  <div class="ip-input-container">
    <div class="ip-input-row">
      <label class="ip-label" :for="`ip-${input.id}`">
        {{ index }}
      </label>
      <input
        :id="`ip-${input.id}`"
        type="text"
        :value="input.value"
        :disabled="input.isLoading"
        :class="inputClasses"
        :aria-describedby="input.error ? `error-${input.id}` : undefined"
        @input="handleInput"
        @blur="handleBlur"
      />
      <button
        v-if="onRemove"
        class="remove-button"
        @click="onRemove(input.id)"
        title="Remove IP input"
      >
        X
      </button>
      <div 
        v-if="input.isLoading" 
        class="spinner" 
        aria-label="Loading" 
        role="status" 
      />
      <IpResult v-if="input.result" :result="input.result" />
    </div>

    <div 
      v-if="input.error" 
      :id="`error-${input.id}`" 
      class="error-message" 
      role="alert"
    >
      {{ input.error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import IpResult from './IpResult.vue'
import type { IpInput } from '../types'
import { useIpLookup } from '../composables/useIpLookup'

interface Props {
  input: IpInput
  index: number
  onRemove?: (id: string) => void
  onUpdate: (input: IpInput) => void
}

const props = defineProps<Props>()

const { handleBlur: handleIpBlur } = useIpLookup(props.onUpdate)

const inputClasses = computed(() => [
  'ip-input',
  {
    'error': props.input.error,
    'success': props.input.result
  }
])

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement
  const updatedInput = { ...props.input, value: target.value }
  props.onUpdate(updatedInput)
}

const handleBlur = (event: Event) => {
  const target = event.target as HTMLInputElement
  handleIpBlur(props.input, target.value)
}
</script>
