// packages/react-app/src/components/TimezoneClockLive.tsx
import React, { useState, useEffect } from "react";

interface TimezoneClockProps {
  timezone: string;
}

export const TimezoneClockLive: React.FC<TimezoneClockProps> = React.memo(
  ({ timezone }) => {
    const [time, setTime] = useState<string>("");

    useEffect(() => {
      const updateTime = () => {
        try {
          const now = new Date();
          const timeString = now.toLocaleTimeString("en-US", {
            timeZone: timezone,
            hour12: false,
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
          });
          setTime(timeString);
        } catch {
          setTime("Invalid timezone");
        }
      };

      updateTime();
      const interval = setInterval(updateTime, 1000);

      return () => clearInterval(interval);
    }, [timezone]);

    return <div className="current-time">{time}</div>;
  }
);

// packages/vue-app/src/components/TimezoneClockLive.vue
<template>
  <div class="current-time">
    {{ time }}
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'

interface Props {
  timezone: string
}

const props = defineProps<Props>()

const time = ref<string>('')
let interval: NodeJS.Timeout | null = null

const updateTime = () => {
  try {
    const now = new Date()
    const timeString = now.toLocaleTimeString('en-US', {
      timeZone: props.timezone,
      hour12: false,
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit'
    })
    time.value = timeString
  } catch {
    time.value = 'Invalid timezone'
  }
}

const startClock = () => {
  updateTime()
  interval = setInterval(updateTime, 1000)
}

const stopClock = () => {
  if (interval) {
    clearInterval(interval)
    interval = null
  }
}

onMounted(() => {
  startClock()
})

onUnmounted(() => {
  stopClock()
})

watch(() => props.timezone, () => {
  stopClock()
  startClock()
})
</script>
