// packages/vue-app/src/App.vue
<template>
  <div class="app">
    <header class="header">
      <h1>IP Lookup Tool</h1>
      <p>Enter one or more IP addresses to get their country</p>
      <button class="add-button" @click="addInput" title="Add IP input">
        + Add
      </button>
    </header>

    <main class="ip-lookup">
      <IpInputField
        v-for="(input, index) in inputs"
        :key="input.id"
        :input="input"
        :index="index + 1"
        :on-update="updateInput"
        :on-remove="canRemoveInputs ? removeInput : undefined"
      />
    </main>
  </div>
</template>

<script setup lang="ts">
import IpInputField from './components/IpInputField.vue'
import { useIpInputFields } from './composables/useIpInputFields'

const { inputs, addInput, removeInput, updateInput, canRemoveInputs } = useIpInputFields()
</script>

// packages/react-app/src/App.tsx
import React from "react";
import { IpInputField } from "./components";
import { useIpInputFields } from "./hooks/useIpInputFields";

const App: React.FC = () => {
  const { inputs, addInput, removeInput, updateInput } = useIpInputFields();

  return (
    <div className="app">
      <header className="header">
        <h1>IP Lookup Tool</h1>
        <p>Enter one or more IP addresses to get their country</p>
        <button className="add-button" onClick={addInput} title="Add IP input">
          + Add
        </button>
      </header>

      <main className="ip-lookup">
        {inputs.map((input, index) => (
          <IpInputField
            key={input.id}
            input={input}
            index={index + 1}
            onUpdate={updateInput}
            onRemove={inputs.length > 1 ? removeInput : undefined}
          />
        ))}
      </main>
    </div>
  );
};

export default App;
